# Generated by Django 4.1 on 2022-09-24 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=16)),
                ('password_hash', models.CharField(max_length=64)),
                ('avatar', models.FileField(blank=True, upload_to='profile/%Y/%m/%D/')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
