# Generated by Django 4.1 on 2022-09-27 08:23

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(upload_to=account.models.PathAndRename('profile/')),
        ),
    ]
