# Generated by Django 4.1 on 2022-09-25 10:00

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_image_rename_function'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, default='default.png', upload_to=account.models.PathAndRename('profile/')),
        ),
    ]
