# Generated by Django 4.1 on 2022-09-25 10:04

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_image_default_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(default='default.png', upload_to=account.models.PathAndRename('profile/')),
        ),
    ]
