# Generated by Django 4.1 on 2022-09-27 08:32

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, default='250', editable=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, default='250', editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=account.models.PathAndRename('profile/')),
        ),
    ]
