# Generated by Django 4.1 on 2022-09-27 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_image_height_user_image_width_alter_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='user',
            name='image_width',
        ),
    ]
