# Generated by Django 4.1 on 2022-09-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_user_image_height_remove_user_image_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about_us',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AddField(
            model_name='user',
            name='website_url',
            field=models.URLField(blank=True, max_length=256),
        ),
    ]
