# Generated by Django 4.1 on 2022-09-27 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_user_about_us_user_website_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='about_us',
            new_name='about_me',
        ),
    ]
