# Generated by Django 4.1 on 2022-09-27 21:50

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_rename_about_us_user_about_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.PathAndRename('profile/')),
        ),
    ]
