# Generated by Django 4.1 on 2022-09-24 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('core', '0002_remove_post_image_name_remove_user_image_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='posted_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
