# Generated by Django 4.1 on 2022-09-25 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_post_posted_user_id_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='posted_user_id',
            new_name='posted_user',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, upload_to='posts/'),
        ),
    ]
