# Generated by Django 4.1 on 2022-09-25 07:39

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_changed_user_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, upload_to=core.models.PathAndRename('/posts')),
        ),
    ]
