# Generated by Django 4.1 on 2022-09-26 20:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_number', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('ip', models.CharField(default='192.168.56.1', max_length=256)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_for', to='post.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acted_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
