# Generated by Django 4.1 on 2022-09-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        ('post', '0002_postaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='tag.tag'),
        ),
    ]
