# Generated by Django 4.1 on 2022-09-27 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hashed_permalink',
            field=models.CharField(blank=True, default=None, max_length=16, null=True),
        ),
    ]
