# Generated by Django 4.1 on 2022-09-27 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_hashed_permalink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hashed_permalink',
            field=models.CharField(default=None, max_length=16, unique=True),
        ),
    ]
