# Generated by Django 4.1 on 2022-09-29 16:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0006_alter_post_hashed_permalink'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=512)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('ip', models.GenericIPAddressField()),
                ('for_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='post.post')),
                ('sub_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='post.postcomment')),
                ('who_sent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_sent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
